#!/usr/bin/env bash
# ===========================================================================
# Engine Platform — Credential Generator
# ===========================================================================
# Generates cryptographically secure credentials for all platform services.
#
# Usage:
#   ./scripts/generate-credentials.sh              # Output .env format to stdout
#   ./scripts/generate-credentials.sh > .env       # Write directly to .env file
#   ./scripts/generate-credentials.sh --format=k8s-secrets > secrets.yaml
#
# Requirements:
#   - openssl (required)
#   - python3 (optional — used for Airflow Fernet key; falls back to openssl)
#
# See docs/CREDENTIALS.md for full documentation.
# ===========================================================================
set -euo pipefail

FORMAT="${1:-env}"
# Normalize --format=xxx to just the value
FORMAT="${FORMAT#--format=}"

# ── Helpers ────────────────────────────────────────────────────────────

rand_base64() {
    local bytes="${1:-32}"
    openssl rand -base64 "$bytes" | tr -d '\n'
}

rand_hex() {
    local bytes="${1:-32}"
    openssl rand -hex "$bytes" | tr -d '\n'
}

rand_password() {
    # URL-safe base64, 16 bytes = ~22 chars
    openssl rand -base64 16 | tr -d '\n/+=' | head -c 20
    echo -n ""
}

generate_fernet_key() {
    # Airflow Fernet key must be URL-safe base64 encoded 32-byte key
    if command -v python3 &>/dev/null; then
        python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
            || openssl rand -base64 32 | tr -d '\n'
    else
        openssl rand -base64 32 | tr -d '\n'
    fi
}

# ── Validate prerequisites ─────────────────────────────────────────────

if ! command -v openssl &>/dev/null; then
    echo "ERROR: openssl is required but not found in PATH." >&2
    exit 1
fi

# ── Generate all credentials ───────────────────────────────────────────

# Database passwords
POSTGRES_PASSWORD="$(rand_base64 24)"
AIML_POSTGRES_PASSWORD="$(rand_base64 24)"

# Platform Manager
DEFAULT_API_KEY="pk_$(rand_base64 32)"
JWT_SECRET="$(rand_base64 48)"

# Airflow
AIRFLOW_FERNET_KEY="$(generate_fernet_key)"
AIRFLOW_WEBSERVER_SECRET="$(rand_base64 32)"
AIRFLOW_ADMIN_PASSWORD="$(rand_password)"

# Langfuse
LANGFUSE_NEXTAUTH_SECRET="$(rand_base64 32)"
LANGFUSE_SALT="$(rand_base64 32)"
LANGFUSE_INIT_USER_PASSWORD="$(rand_password)"
LANGFUSE_INIT_PROJECT_PUBLIC_KEY="pk-lf-$(rand_hex 16)"
LANGFUSE_INIT_PROJECT_SECRET_KEY="sk-lf-$(rand_hex 16)"

# Langflow
LANGFLOW_SUPERUSER_PASSWORD="$(rand_password)"

# n8n
N8N_DEFAULT_USER_PASSWORD="$(rand_password)"
N8N_ENCRYPTION_KEY="$(rand_hex 32)"

# Grafana
GRAFANA_ADMIN_PASSWORD="$(rand_password)"

# ── Output ─────────────────────────────────────────────────────────────

if [[ "$FORMAT" == "k8s-secrets" ]]; then
    cat <<YAML
# Generated by scripts/generate-credentials.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# WARNING: This file contains secrets. Do NOT commit to version control.

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  POSTGRES_USER: "engine_user"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "engine_platform"

---
apiVersion: v1
kind: Secret
metadata:
  name: aiml-postgres-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  AIML_POSTGRES_USER: "aiml_user"
  AIML_POSTGRES_PASSWORD: "${AIML_POSTGRES_PASSWORD}"
  AIML_POSTGRES_DB: "aiml"

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-manager-secrets
  namespace: engine-platform
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  DEFAULT_API_KEY: "${DEFAULT_API_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  AIML_POSTGRES_PASSWORD: "${AIML_POSTGRES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  AIRFLOW_FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
  AIRFLOW_WEBSERVER_SECRET: "${AIRFLOW_WEBSERVER_SECRET}"
  AIRFLOW_ADMIN_PASSWORD: "${AIRFLOW_ADMIN_PASSWORD}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  LANGFUSE_NEXTAUTH_SECRET: "${LANGFUSE_NEXTAUTH_SECRET}"
  LANGFUSE_SALT: "${LANGFUSE_SALT}"
  LANGFUSE_INIT_USER_PASSWORD: "${LANGFUSE_INIT_USER_PASSWORD}"
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}"
  LANGFUSE_INIT_PROJECT_SECRET_KEY: "${LANGFUSE_INIT_PROJECT_SECRET_KEY}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  N8N_DEFAULT_USER_PASSWORD: "${N8N_DEFAULT_USER_PASSWORD}"
  N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: langflow-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  LANGFLOW_SUPERUSER_PASSWORD: "${LANGFLOW_SUPERUSER_PASSWORD}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
YAML

else
    # Default: .env format
    cat <<ENV
# ===========================================================================
# Engine Platform — Generated Credentials
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ===========================================================================
# This file was generated by scripts/generate-credentials.sh
# WARNING: Contains secrets. Do NOT commit to version control.
# ===========================================================================

# ===========================================================================
# Authentication — set AUTH_MODE=api-key for production
# ===========================================================================
AUTH_MODE=api-key
DEFAULT_API_KEY=${DEFAULT_API_KEY}
API_KEY_PREFIX=pk
JWT_SECRET=${JWT_SECRET}

# ===========================================================================
# Main PostgreSQL
# ===========================================================================
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=engine_platform
POSTGRES_USER=engine_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ===========================================================================
# AIML PostgreSQL
# ===========================================================================
AIML_POSTGRES_HOST=aiml-postgres
AIML_POSTGRES_PORT=5432
AIML_POSTGRES_DB=aiml
AIML_POSTGRES_USER=aiml_user
AIML_POSTGRES_PASSWORD=${AIML_POSTGRES_PASSWORD}

# ===========================================================================
# Airflow
# ===========================================================================
AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
AIRFLOW_WEBSERVER_SECRET=${AIRFLOW_WEBSERVER_SECRET}
AIRFLOW_ADMIN_USERNAME=airflow
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AIRFLOW_EXPOSE_CONFIG=false

# ===========================================================================
# Langfuse
# ===========================================================================
LANGFUSE_NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
LANGFUSE_SALT=${LANGFUSE_SALT}
LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_INIT_USER_PASSWORD}
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${LANGFUSE_INIT_PROJECT_SECRET_KEY}

# ===========================================================================
# Langflow
# ===========================================================================
LANGFLOW_SUPERUSER=admin
LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD}
LANGFLOW_AUTO_LOGIN=false

# ===========================================================================
# n8n
# ===========================================================================
N8N_DEFAULT_USER_PASSWORD=${N8N_DEFAULT_USER_PASSWORD}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_SECURE_COOKIE=true

# ===========================================================================
# Grafana
# ===========================================================================
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
GRAFANA_ANONYMOUS_ENABLED=false

# ===========================================================================
# Open WebUI
# ===========================================================================
WEBUI_AUTH=true
ENV

fi
